### ISSUE TITLE
shared resource warning for using same namespace for multiple microservices

### ISSUE THREAD

**Issue by JacekZubielik** [JacekZubielik/k8s-argocd-autopilot-playground#9]
```
helmCharts:
  - name: binance-proxy
    version: 0.0.4
    repo: https://jacekzubielik.github.io/jz-helm-charts
    releaseName: binance-proxy
    includeCRDs: false
    valuesFile: values.yaml
```
